/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;
/**
 *
 * @author SONEVILAY
 */
public class Calculator extends javax.swing.JFrame {
    double show;
    String valueA, valueB,valueC="";

    /**
  
     */
    public Calculator() {
        super("Calculator");
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtresult = new javax.swing.JTextField();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num1 = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtresult.setEditable(false);
        txtresult.setBackground(new java.awt.Color(204, 204, 255));
        txtresult.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        txtresult.setText("0");
        txtresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresultActionPerformed(evt);
            }
        });
        jPanel1.add(txtresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 13, 218, -1));

        num7.setBackground(new java.awt.Color(102, 204, 255));
        num7.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });
        jPanel1.add(num7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 122, 47, 39));

        num8.setBackground(new java.awt.Color(102, 204, 255));
        num8.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });
        jPanel1.add(num8, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 122, 47, 39));

        num0.setBackground(new java.awt.Color(102, 204, 255));
        num0.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        num0.setText("0");
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });
        jPanel1.add(num0, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 268, 47, 39));

        plus.setBackground(new java.awt.Color(102, 204, 255));
        plus.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        jPanel1.add(plus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 47, 39));

        minus.setBackground(new java.awt.Color(102, 204, 255));
        minus.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        jPanel1.add(minus, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 122, 47, 39));

        num6.setBackground(new java.awt.Color(102, 204, 255));
        num6.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });
        jPanel1.add(num6, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 172, 47, 39));

        num5.setBackground(new java.awt.Color(102, 204, 255));
        num5.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        jPanel1.add(num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 172, 47, 39));

        num4.setBackground(new java.awt.Color(102, 204, 255));
        num4.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        jPanel1.add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 172, 47, 39));

        multiply.setBackground(new java.awt.Color(102, 204, 255));
        multiply.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        multiply.setText("x");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });
        jPanel1.add(multiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 172, 47, 39));

        num3.setBackground(new java.awt.Color(102, 204, 255));
        num3.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        jPanel1.add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 222, 47, 39));

        num2.setBackground(new java.awt.Color(102, 204, 255));
        num2.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        jPanel1.add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 222, 47, 39));

        num1.setBackground(new java.awt.Color(102, 204, 255));
        num1.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        jPanel1.add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 222, 47, 39));

        divide.setBackground(new java.awt.Color(102, 204, 255));
        divide.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });
        jPanel1.add(divide, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 222, 47, 39));

        Clear.setBackground(new java.awt.Color(102, 204, 255));
        Clear.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        Clear.setText("C");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 92, 39));

        delete.setBackground(new java.awt.Color(102, 204, 255));
        delete.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        delete.setText("<----");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 60, 40));

        equal.setBackground(new java.awt.Color(102, 204, 255));
        equal.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        jPanel1.add(equal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 100, -1));

        num9.setBackground(new java.awt.Color(102, 204, 255));
        num9.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });
        jPanel1.add(num9, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 122, 47, 39));

        num10.setBackground(new java.awt.Color(102, 204, 255));
        num10.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        num10.setText(".");
        num10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num10ActionPerformed(evt);
            }
        });
        jPanel1.add(num10, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 268, 47, 39));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        txtresult.setText("0");
        valueA = "";
        valueB = "";
        valueC="0";

        // TODO add your handling code here:
    }//GEN-LAST:event_ClearActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
        if(valueA=="A" && valueC=="1"){
         double a = Double.parseDouble(txtresult.getText());
         show = show+a;
         String b=String.valueOf(show);
         int length=b.length();
         String sub=b.substring(length-2);
         if(sub.equals(".0")){
          String sub1=b.substring(0,length-2);
          txtresult.setText(sub1);
         }else{
         txtresult.setText(b);
         }
        }
         else if (valueA=="B" && valueC=="1"){
         double a = Double.parseDouble(txtresult.getText());
         show = show-a;
         String b=String.valueOf(show);
         int length=b.length();
         String sub=b.substring(length-2);
         if(sub.equals(".0")){
          String sub1=b.substring(0,length-2);
          txtresult.setText(sub1);
        }else{
         txtresult.setText(b);
         }
         }
         else if (valueA=="C" && valueC=="1"){
         double a = Double.parseDouble(txtresult.getText());
         show = show*a;
         String b=String.valueOf(show);
         int length=b.length();
         String sub=b.substring(length-2);
         if(sub.equals(".0")){
          String sub1=b.substring(0,length-2);
          txtresult.setText(sub1);
        }else{
         txtresult.setText(b);
         }
         }
          else if (valueA=="D" && valueC=="1"){
         double a = Double.parseDouble(txtresult.getText());
         show = show/a;
         String b=String.valueOf(show);
         int length=b.length();
         String sub=b.substring(length-2);
         if(sub.equals(".0")){
          String sub1=b.substring(0,length-2);
          txtresult.setText(sub1);
        }
         else{
         txtresult.setText(b);
         }
         }
        
        double a = Double.parseDouble(txtresult.getText());
        show = a;
        valueA = "B";
        valueB = "B";
        valueC="0";
    }//GEN-LAST:event_minusActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        // TODO add your handling code here:
         if(valueA=="A" && valueC=="1"){
         double a = Double.parseDouble(txtresult.getText());
         show = show+a;
         String b=String.valueOf(show);
         int length=b.length();
         String sub=b.substring(length-2);
         if(sub.equals(".0")){
          String sub1=b.substring(0,length-2);
          txtresult.setText(sub1);
         }else{
         txtresult.setText(b);
         }
        }
         else if (valueA=="B" && valueC=="1"){
         double a = Double.parseDouble(txtresult.getText());
         show = show-a;
         String b=String.valueOf(show);
         int length=b.length();
         String sub=b.substring(length-2);
         if(sub.equals(".0")){
          String sub1=b.substring(0,length-2);
          txtresult.setText(sub1);
        }else{
         txtresult.setText(b);
         }
         }
         else if (valueA=="C" && valueC=="1"){
         double a = Double.parseDouble(txtresult.getText());
         show = show*a;
         String b=String.valueOf(show);
         int length=b.length();
         String sub=b.substring(length-2);
         if(sub.equals(".0")){
          String sub1=b.substring(0,length-2);
          txtresult.setText(sub1);
        }else{
         txtresult.setText(b);
         }
         }
          else if (valueA=="D" && valueC=="1"){
         double a = Double.parseDouble(txtresult.getText());
         show = show/a;
         String b=String.valueOf(show);
         int length=b.length();
         String sub=b.substring(length-2);
         if(sub.equals(".0")){
          String sub1=b.substring(0,length-2);
          txtresult.setText(sub1);
        }else{
         txtresult.setText(b);
         }
         }
        double a = Double.parseDouble(txtresult.getText());
        show = a;
        valueA = "D";
        valueB = "D";
        valueC="0";
    }//GEN-LAST:event_divideActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
        if(valueA=="A" || valueA=="B" || valueA=="C" || valueA=="D"){
         String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("2");
            valueB = "";
            valueC="1";
        } else {
            txtresult.setText(a + "2");
            valueC="1";
        }
        }else{
        String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("2");
            valueB = "";
        } else {
            txtresult.setText(a + "2");
        }
        }
    }//GEN-LAST:event_num2ActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
        if(valueA=="A" || valueA=="B" || valueA=="C" || valueA=="D"){
         String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("1");
            valueB = "";
            valueC="1";
        } else {
            txtresult.setText(a + "1");
            valueC="1";
        }  
        }else {
        String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("1");
            valueB = "";
        } else {
            txtresult.setText(a + "1");
        }
        }
    }//GEN-LAST:event_num1ActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        if(valueA=="A" && valueC=="1"){
         double a = Double.parseDouble(txtresult.getText());
         show = show+a;
         String b=String.valueOf(show);
         int length=b.length();
         String sub=b.substring(length-2);
         if(sub.equals(".0")){
          String sub1=b.substring(0,length-2);
          txtresult.setText(sub1);
         }else{
         txtresult.setText(b);
         }
        }
         else if (valueA=="B" && valueC=="1"){
         double a = Double.parseDouble(txtresult.getText());
         show = show-a;
         String b=String.valueOf(show);
         int length=b.length();
         String sub=b.substring(length-2);
         if(sub.equals(".0")){
          String sub1=b.substring(0,length-2);
          txtresult.setText(sub1);
        }else{
         txtresult.setText(b);
         }
         }
         else if (valueA=="C" && valueC=="1"){
         double a = Double.parseDouble(txtresult.getText());
         show = show*a;
         String b=String.valueOf(show);
         int length=b.length();
         String sub=b.substring(length-2);
         if(sub.equals(".0")){
          String sub1=b.substring(0,length-2);
          txtresult.setText(sub1);
        }else{
         txtresult.setText(b);
         }
         }
          else if (valueA=="D" && valueC=="1"){
         double a = Double.parseDouble(txtresult.getText());
         show = show/a;
         String b=String.valueOf(show);
         int length=b.length();
         String sub=b.substring(length-2);
         if(sub.equals(".0")){
          String sub1=b.substring(0,length-2);
          txtresult.setText(sub1);
        }else{
         txtresult.setText(b);
         }
         }
         double a=Double.parseDouble(txtresult.getText());
        show = a;
        valueA = "A";
        valueB = "A";
        valueC="0";
        
    }//GEN-LAST:event_plusActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        // TODO add your handling code here:
        if (valueA == "A") {
            double a = Double.parseDouble(txtresult.getText());
            show = show + a;
            valueA = "";
            valueB = "A";
        } else if (valueA == "B") {
            double a = Double.parseDouble(txtresult.getText());
            show = show - a;
            valueA = "";
            valueB = "B";
        } else if (valueA == "C") {
            double a = Double.parseDouble(txtresult.getText());
            show = show * a;
            valueA = "";
            valueB = "C";
        } else if (valueA == "D") {
            double a = Double.parseDouble(txtresult.getText());
            show = show / a;
            valueA = "";
            valueB = "D";
        }
         String a=String.valueOf(show);
         int length=a.length();
         String b=a.substring(length-2);
         if(b.equals(".0")){
         String c=a.substring(0,length-2);
         txtresult.setText(c);
         }
         else{
         txtresult.setText(a);
         }
    }//GEN-LAST:event_equalActionPerformed

    private void txtresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtresultActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        // TODO add your handling code here:
        if(valueA=="A" || valueA=="B" || valueA=="C" || valueA=="D"){
         String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("3");
            valueB = "";
            valueC="1";
        } else {
            txtresult.setText(a + "3");
            valueC="1";
        }
        }else{
        String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("3");
            valueB = "";
        } else {
            txtresult.setText(a + "3");
        }
        }
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        // TODO add your handling code here:
        if(valueA=="A" || valueA=="B" || valueA=="C" || valueA=="D"){
         String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("4");
            valueB = "";
            valueC="1";
        } else {
            txtresult.setText(a + "4");
            valueC="1";
        }
        }else{
        String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("4");
            valueB = "";
        } else {
            txtresult.setText(a+ "4");
        }
        }
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        // TODO add your handling code here:
        if(valueA=="A" || valueA=="B" || valueA=="C" || valueA=="D"){
         String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("5");
            valueB = "";
            valueC="1";
        } else {
            txtresult.setText(a + "5");
            valueC="1";
        }
        }else{
        String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("5");
            valueB = "";
        } else {
            txtresult.setText(a + "5");
        }
        }
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        // TODO add your handling code here:
        if(valueA=="A" || valueA=="B" || valueA=="C" || valueA=="D"){
         String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("6");
            valueB = "";
            valueC="1";
        } else {
            txtresult.setText(a + "6");
            valueC="1";
        }
        }else{
        String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("6");
            valueB = "";
        } else {
            txtresult.setText(a + "6");
        }
        }
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        // TODO add your handling code here:
        if(valueA=="A" || valueA=="B" || valueA=="C" || valueA=="D"){
         String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("7");
            valueB = "";
            valueC="1";
        } else {
            txtresult.setText(a + "7");
            valueC="1";
        }
        }else{
        String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("7");
            valueB = "";
        } else {
            txtresult.setText(a + "7");
        }
        }
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        // TODO add your handling code here:
        if(valueA=="A" || valueA=="B" || valueA=="C" || valueA=="D"){
         String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("8");
            valueB = "";
            valueC="1";
        } else {
            txtresult.setText(a + "8");
            valueC="1";
        }
        }else{
        String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("8");
            valueB = "";
        } else {
            txtresult.setText(a + "8");
        }
        }
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        // TODO add your handling code here:
        if(valueA=="A" || valueA=="B" || valueA=="C" || valueA=="D"){
         String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("9");
            valueB = "";
            valueC="1";
        } else {
            txtresult.setText(a + "9");
            valueC="1";
        }
        }else{
        String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("9");
            valueB = "";
        } else {
            txtresult.setText(a + "9");
        }
        }
    }//GEN-LAST:event_num9ActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        // TODO add your handling code here:
        if(valueA=="A" || valueA=="B" || valueA=="C" || valueA=="D"){
         String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("0");
            valueB = "";
            valueC="1";
        } else {
            txtresult.setText(a + "0");
            valueC="1";
        }
        }else{
        String a = txtresult.getText();
        if (a.equals("0") || valueB == ("A") || valueB == ("B") || valueB == ("C") || valueB == ("D")) {
            txtresult.setText("0");
            valueB = "";
        } else {
            txtresult.setText(a + "0");
        }
        }
    }//GEN-LAST:event_num0ActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        // TODO add your handling code here:
        if(valueA=="A" && valueC=="1"){
         double a = Double.parseDouble(txtresult.getText());
         show = show+a;
         String b=String.valueOf(show);
         int length=b.length();
         String sub=b.substring(length-2);
         if(sub.equals(".0")){
          String sub1=b.substring(0,length-2);
          txtresult.setText(sub1);
         }else{
         txtresult.setText(b);
         }
        }
         else if (valueA=="B" && valueC=="1"){
         double a = Double.parseDouble(txtresult.getText());
         show = show-a;
         String b=String.valueOf(show);
         int length=b.length();
         String sub=b.substring(length-2);
         if(sub.equals(".0")){
          String sub1=b.substring(0,length-2);
          txtresult.setText(sub1);
        }else{
         txtresult.setText(b);
         }
         }
         else if (valueA=="C" && valueC=="1"){
         double a = Double.parseDouble(txtresult.getText());
         show = show*a;
         String b=String.valueOf(show);
         int length=b.length();
         String sub=b.substring(length-2);
         if(sub.equals(".0")){
          String sub1=b.substring(0,length-2);
          txtresult.setText(sub1);
        }else{
         txtresult.setText(b);
         }
         }
          else if (valueA=="D" && valueC=="1"){
         double a = Double.parseDouble(txtresult.getText());
         show = show/a;
         String b=String.valueOf(show);
         int length=b.length();
         String sub=b.substring(length-2);
         if(sub.equals(".0")){
          String sub1=b.substring(0,length-2);
          txtresult.setText(sub1);
        }else{
         txtresult.setText(b);
         }
         }
        double a = Double.parseDouble(txtresult.getText());
        show = a;
        valueA = "C";
        valueB = "C";
        valueC="0";
    }//GEN-LAST:event_multiplyActionPerformed

    private void num10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num10ActionPerformed
        // TODO add your handling code here:
        String a=String.valueOf(txtresult.getText());
        int length=a.length();
        int b=1;
        for(int i=length; i>0;i--){
         String sub=a.substring(i-1,i);
         if(".".equals(sub)){
             b=0;
             i=0;
         }
        }
        if (txtresult.getText() == "") {
            txtresult.setText(String.valueOf("0."));
        } else if (b!=0){
            String n = txtresult.getText();
            txtresult.setText(String.valueOf(n + "."));
        }
    }//GEN-LAST:event_num10ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
String a=String.valueOf(txtresult.getText());
int length=a.length();
String sub=a.substring(0);
if(length==1){
 txtresult.setText("0");
}
else if(!"0".equals(sub)){
String sub1=a.substring(0,length-1);
txtresult.setText(sub1);
}
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton divide;
    private javax.swing.JButton equal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minus;
    private javax.swing.JButton multiply;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num10;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JButton plus;
    private javax.swing.JTextField txtresult;
    // End of variables declaration//GEN-END:variables
}
